name: FastApi-tutorials

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration
    env:
      DATABASE_URL: sqlite:///blog.db
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: HS256
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Testing
        run: pytest ./tests/

  Security_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-result.json

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-result
          path: trivy-result.json

  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alexandrepaulkouame/fastapi-tutorials:latest

  docker_deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: docker_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: mkdir -p /root/projects/fastapi-tutorials

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./docker-compose.yml"
          target: "/root/projects/fastapi-tutorials"

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/projects/fastapi-tutorials

            cat > .env << EOF
            DATABASE_URL=sqlite:///blog.db
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ALGORITHM=HS256
            EOF

            docker compose pull
            docker compose down
            docker compose up -d
